# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Queque < Formula
  def caveats
  <<~EOS
    To enable the ?? trigger, add the shell integration to your .zshrc:
      qq init zsh >> ~/.zshrc
      source ~/.zshrc
    Then set your Anthropic API key:
      export ANTHROPIC_API_KEY="sk-ant-..."
  EOS
end

  desc "Your in terminal ai helper"
  homepage "https://github.com/k-leumas/queque"
  url "https://github.com/k-leumas/queque/archive/refs/tags/v0.3.3.tar.gz"
  sha256 "989382a618f5fa4c4e6ebb45d546f1dd4810e3aa1309e3d983a9fadc0a577b77"

  depends_on "jq"
  depends_on "node"

  def install
    system "npm", "install", "--ignore-scripts", "--loglevel=error"
system "node_modules/.bin/tsup"
system "npm", "install", *std_npm_args, "--loglevel=error"
bin.install_symlink libexec/"lib/node_modules/@k-leumas/queque-cli/dist/cli/main.js" => "qq"
(share/"queque").install "shell/zsh/queque.zsh"
  end

  test do
    assert_match "queque", shell_output("#{bin}/qq --version")
  end
end
