# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Queque < Formula
  def caveats
  <<~EOS
    To enable the ?? trigger, add the shell integration to your .zshrc:
      qq init zsh >> ~/.zshrc
      source ~/.zshrc
    Then set your Anthropic API key:
      export ANTHROPIC_API_KEY="sk-ant-..."
  EOS
end

  desc "Your in terminal ai helper"
  homepage "https://github.com/k-leumas/queque"
  url "https://github.com/k-leumas/queque/archive/refs/tags/v0.2.7.tar.gz"
  sha256 "d9d3a78cc8d84dd32473e5e61d36a7f9e2d4806acf913f41d1b51a36575f94f8"

  depends_on "jq"
  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
bin.install_symlink Dir["#{libexec}/bin/*"]
(share/"queque").install "shell/zsh/queque.zsh"
  end

  test do
    assert_match "queque", shell_output("#{bin}/qq --version")
  end
end
